name: CI/CD con Serveo

on:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar ESLint
        run: npx eslint .  # Este paso falla si ESLint encuentra errores

  test:
    needs: eslint  # Este paso depende de que el job 'eslint' pase correctamente
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test
 
  docker-validation:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen Docker
        run: docker build -t sriverar03/api-basica .

      - name: Escanear imagen Docker con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sriverar03/api-basica
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

  build-and-deploy:
    needs: docker-validation  # Este paso depende de que el job 'test' pase correctamente
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Autenticarse en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t sriverar03/api-basica .

      - name: Subir imagen a Docker Hub
        run: docker push sriverar03/api-basica

      - name: Hacer deploy a WSL vía Serveo con contraseña
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker pull sriverar03/api-basica
            docker stop api-basica1 || true
            docker rm api-basica1 || true
            docker run -d --name api-basica1 -p 3000:3000 sriverar03/api-basica
